### ISSUE TITLE
Error when running `ruby render.rb`

### ISSUE THREAD

**Issue by aramprice** [ragaskar/trivial#1]
# Error info
```
ruby render.rb ~/workspace/scan > scan.csv
Traceback (most recent call last):
	6: from render.rb:10:in `<main>'
	5: from trivial/models/trivy_json_parser.rb:8:in `parse'
	4: from trivial/models/trivy_json_parser.rb:8:in `each'
	3: from trivial/models/trivy_json_parser.rb:34:in `block in parse'
	2: from trivial/models/trivy_json_parser.rb:34:in `each'
	1: from trivial/models/trivy_json_parser.rb:35:in `block (2 levels) in parse'
trivial/models/trivy_json_parser.rb:35:in `[]': no implicit conversion of String into Integer (TypeError)
```

# Environment info
```
; uname -a
Darwin laptop.local 20.6.0 Darwin Kernel Version 20.6.0: Tue Oct 12 18:33:42 PDT 2021; root:xnu-7195.141.8~1/RELEASE_X86_64 x86_64

; ruby -v
ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin20]

; git lg -1
* [446c8e2] (HEAD -> main, origin/main, origin/HEAD) 2021-03-23 14:35:50 -0700 by Rajan Agaskar. Display "Fixed Version" and "Installed Version"
```

**Comment by ragaskar** [comment]
PRs accepted. ;)

**Comment by ragaskar** [comment]
fixed in main.
